apiVersion: apps/v1
kind: Deployment
metadata:
  name: nclcloud-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
       — name: nclcoudapp
         image: nclcloudcomputing/javabenchmarkapp
---
apiVersion: v1
kind: Service
metadata:
  name: nclcloud-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nclcoudapp
  ports:
    - procotcol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
