apiVersion: apps/v1
kind: Deployment
metadata:
  name: nclcloud-deployment
  labels:
    app: nclcloudapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
      - name: nclcloudapp
        image: nclcloudcomputing/javabenchmarkapp:latest
        
---

apiVersion: v1
kind: Service
metadata:
  name: nclcloud-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: cloud-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
